<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="AmbiguousMatchException.xml" source-language="en-US" target-language="zh-TW">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5911cf30906a42c5385f0853056fca9293ff264b8.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">911cf30906a42c5385f0853056fca9293ff264b8</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netcore-1.0,netcore-1.1,netcore-2.0,netcore-2.1,netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,netstandard-1.0,netstandard-1.1,netstandard-1.2,netstandard-1.3,netstandard-1.4,netstandard-1.5,netstandard-1.6,netstandard-2.0,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Reflection.AmbiguousMatchException">
          <source>The exception that is thrown when binding to a member results in more than one member matching the binding criteria.</source>
          <target state="translated">繫結至成員而使得一個以上的成員符合繫結準則時，所擲回的例外狀況。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" uid="T:System.Reflection.AmbiguousMatchException">
          <source>This class cannot be inherited.</source>
          <target state="translated">這個類別無法被繼承。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Reflection.AmbiguousMatchException">
          <source><ph id="ph1">`AmbiguousMatchException`</ph> uses the HRESULT COR_E_AMBIGUOUSMATCH which has the value 0x8000211D.</source>
          <target state="translated"><ph id="ph1">`AmbiguousMatchException`</ph> 會使用 HRESULT COR_E_AMBIGUOUSMATCH 0x8000211D 的值。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Reflection.AmbiguousMatchException">
          <source>An <ph id="ph1">`AmbiguousMatchException`</ph> is thrown when a member is invoked late-bound and multiple overloads satisfy the binding criteria, or when more than one member matches the binding criteria passed to a reflection method that can return only a single result (for example, <ph id="ph2">&lt;xref:System.Type.GetMethod%2A?displayProperty=nameWithType&gt;</ph> or <ph id="ph3">&lt;xref:System.Type.GetProperty%2A?displayProperty=nameWithType&gt;</ph>).</source>
          <target state="translated"><ph id="ph1">`AmbiguousMatchException`</ph>晚期繫結叫用成員，而多個多載符合繫結準則時，或一個以上的成員符合傳遞至反映方法可傳回單一結果的繫結準則時，會擲回 (例如， <ph id="ph2">&lt;xref:System.Type.GetMethod%2A?displayProperty=nameWithType&gt;</ph>或<ph id="ph3">&lt;xref:System.Type.GetProperty%2A?displayProperty=nameWithType&gt;</ph>)。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" uid="T:System.Reflection.AmbiguousMatchException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Reflection.AmbiguousMatchException" /&gt;</ph> class.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.Reflection.AmbiguousMatchException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="M:System.Reflection.AmbiguousMatchException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Reflection.AmbiguousMatchException" /&gt;</ph> class with an empty message string and the root cause exception set to <ph id="ph2">&lt;see langword="null" /&gt;</ph>.</source>
          <target state="translated">使用設定為 <ph id="ph2">&lt;see langword="null" /&gt;</ph> 的空訊息字串和根本原因例外狀況，來初始化 <ph id="ph1">&lt;see cref="T:System.Reflection.AmbiguousMatchException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor">
          <source><ph id="ph1">`AmbiguousMatchException`</ph> inherits from <ph id="ph2">&lt;xref:System.Exception&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">`AmbiguousMatchException`</ph> 繼承自 <ph id="ph2">&lt;xref:System.Exception&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor">
          <source>This constructor sets the properties of the <ph id="ph1">`Exception`</ph> object as shown in the following table.</source>
          <target state="translated">這個建構函式設定的屬性<ph id="ph1">`Exception`</ph>物件下表所示。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor">
          <source>Property</source>
          <target state="translated">屬性</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor">
          <source>Value</source>
          <target state="translated">值</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor">
          <source>The empty string ("").</source>
          <target state="translated">空字串 ("")。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String)">
          <source>A string indicating the reason this exception was thrown.</source>
          <target state="translated">字串，表示這個例外狀況擲回的原因。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Reflection.AmbiguousMatchException" /&gt;</ph> class with its message string set to the given message and the root cause exception set to <ph id="ph2">&lt;see langword="null" /&gt;</ph>.</source>
          <target state="translated">使用在該類別中設定為指定訊息的訊息字串，和設定為 <ph id="ph2">&lt;see langword="null" /&gt;</ph> 的根本原因例外狀況，來初始化 <ph id="ph1">&lt;see cref="T:System.Reflection.AmbiguousMatchException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String)">
          <source><ph id="ph1">`AmbiguousMatchException`</ph> inherits from <ph id="ph2">&lt;xref:System.Exception&gt;</ph>.</source>
          <target state="translated"><ph id="ph1">`AmbiguousMatchException`</ph> 繼承自 <ph id="ph2">&lt;xref:System.Exception&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String)">
          <source>This constructor sets the properties of the <ph id="ph1">`Exception`</ph> object as shown in the following table.</source>
          <target state="translated">這個建構函式設定的屬性<ph id="ph1">`Exception`</ph>物件下表所示。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String)">
          <source>Property</source>
          <target state="translated">屬性</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String)">
          <source>Value</source>
          <target state="translated">值</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String)">
          <source>The <ph id="ph1">`message`</ph> string.</source>
          <target state="translated"><ph id="ph1">`message`</ph>字串。</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解釋例外狀況原因的錯誤訊息。</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">做為目前例外狀況發生原因的例外狀況。</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>inner<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          <target state="translated">如果 <bpt id="p1">&lt;c&gt;</bpt>inner<ept id="p1">&lt;/c&gt;</ept> 參數不是 <ph id="ph1">&lt;see langword="null" /&gt;</ph>，則目前的例外狀況會在處理內部例外狀況的 <ph id="ph2">&lt;see langword="catch" /&gt;</ph> 區塊中引發。</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Reflection.AmbiguousMatchException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">使用指定的錯誤訊息以及造成此例外狀況的內部例外狀況的參考，初始化 <ph id="ph1">&lt;see cref="T:System.Reflection.AmbiguousMatchException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>An exception that is thrown as a direct result of a previous exception should include a reference to the previous exception in the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">被擲回以做為前一個例外狀況直接結果的例外狀況，應該在 <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 屬性中包含對前一個例外狀況的參考。</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id="ph2">`null`</ph> if the <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 屬性會傳回與傳入建構函式中相同的值；如果 <ph id="ph2">`null`</ph> 屬性沒有提供內部例外值給建構函式，則傳回 <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>The following table shows the initial property values for an instance of <ph id="ph1">&lt;xref:System.Reflection.AmbiguousMatchException&gt;</ph>.</source>
          <target state="translated">下表顯示 <ph id="ph1">&lt;xref:System.Reflection.AmbiguousMatchException&gt;</ph> 執行個體的初始屬性值。</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>Property</source>
          <target state="translated">屬性</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>Value</source>
          <target state="translated">值</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>The inner exception reference.</source>
          <target state="translated">內部例外狀況參考。</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>The error message string.</source>
          <target state="translated">錯誤訊息字串。</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>The following example shows two classes, each named <ph id="ph1">`Mymethod`</ph>.</source>
          <target state="translated">下列範例顯示兩個類別中，每個名為<ph id="ph1">`Mymethod`</ph>。</target>       </trans-unit>
        <trans-unit id="131" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>One class takes an integer and the other takes a string.</source>
          <target state="translated">其中一個類別會採用整數和另一個採用字串。</target>       </trans-unit>
        <trans-unit id="132" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>If an integer is passed to <ph id="ph1">`Mymethod`</ph>, the first class is used.</source>
          <target state="translated">如果整數傳遞給<ph id="ph1">`Mymethod`</ph>，則會使用第一個類別。</target>       </trans-unit>
        <trans-unit id="133" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>If a string is passed, the second class is used.</source>
          <target state="translated">如果將字串傳遞時，會使用第二個類別。</target>       </trans-unit>
        <trans-unit id="134" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Reflection.AmbiguousMatchException.#ctor(System.String,System.Exception)">
          <source>If it cannot be determined which <ph id="ph1">`Mymethod`</ph> to use, <ph id="ph2">`AmbiguousMatchException`</ph> is thrown.</source>
          <target state="translated">如果無法判斷其中<ph id="ph1">`Mymethod`</ph>若要使用，<ph id="ph2">`AmbiguousMatchException`</ph>就會擲回。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>