<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="RemotingTimeoutException.xml" source-language="en-US" target-language="zh-TW">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac5c7de839e58677c030609a31048d4f38c244fb03c.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">c7de839e58677c030609a31048d4f38c244fb03c</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7,xamarinandroid-7.1,xamarinios-10.8,xamarinmac-3.0</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Runtime.Remoting.RemotingTimeoutException">
          <source>The exception that is thrown when the server or the client cannot be reached for a previously specified period of time.</source>
          <target state="translated">在一段事先指定的時間內無法連絡到伺服器或用戶端時所擲回的例外狀況。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.Remoting.RemotingTimeoutException">
          <source>The <ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> is thrown when a remoting call does not complete in the specified timeout time.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>遠端呼叫未在指定的逾時時間內完成時，會擲回。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.Remoting.RemotingTimeoutException">
          <source><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> uses the HRESULT COR_E_REMOTING, which has the value 0x8013150B.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> 會使用 HRESULT COR_E_REMOTING，0x8013150B 的值。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.Remoting.RemotingTimeoutException">
          <source><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> uses the default <ph id="ph2">&lt;xref:System.Object.Equals%2A&gt;</ph> implementation, which supports reference equality.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> 使用預設的<ph id="ph2">&lt;xref:System.Object.Equals%2A&gt;</ph>支援參考相等的實作。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Runtime.Remoting.RemotingTimeoutException">
          <source>For a list of initial property values for an instance of <ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>, see the <ph id="ph2">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> constructors.</source>
          <target state="translated">如需執行個體的初始屬性值的清單<ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>，請參閱<ph id="ph2">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>建構函式。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" uid="T:System.Runtime.Remoting.RemotingTimeoutException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.RemotingTimeoutException" /&gt;</ph> class.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.RemotingTimeoutException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.RemotingTimeoutException" /&gt;</ph> class with default properties.</source>
          <target state="translated">使用預設屬性，初始化 <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.RemotingTimeoutException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor">
          <source><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> inherits from the <ph id="ph2">&lt;xref:System.Exception&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> 繼承自<ph id="ph2">&lt;xref:System.Exception&gt;</ph>類別。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor">
          <source>The following table shows initial property values for an instance of the <ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> class:</source>
          <target state="translated">下表顯示的執行個體的初始屬性值<ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>類別：</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor">
          <source>Property</source>
          <target state="translated">屬性</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor">
          <source>Value</source>
          <target state="translated">值</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor">
          <source>Localized error message for <ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph></source>
          <target state="translated">當地語系化的錯誤訊息 <ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph></target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)">
          <source>The message that indicates the reason why the exception occurred.</source>
          <target state="translated">訊息，指出例外狀況為何會發生的理由。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)">
          <source>Initializes a new instance of <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.RemotingTimeoutException" /&gt;</ph> class with a specified message.</source>
          <target state="translated">使用指定的訊息，初始化 <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.RemotingTimeoutException" /&gt;</ph> 的新執行個體。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)">
          <source><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> inherits from the <ph id="ph2">&lt;xref:System.Exception&gt;</ph> class.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> 繼承自<ph id="ph2">&lt;xref:System.Exception&gt;</ph>類別。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)">
          <source>The following table shows initial property values for an instance of the <ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> class:</source>
          <target state="translated">下表顯示的執行個體的初始屬性值<ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>類別：</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)">
          <source>Property Type</source>
          <target state="translated">屬性類型</target>       </trans-unit>
        <trans-unit id="118" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)">
          <source>Condition</source>
          <target state="translated">條件</target>       </trans-unit>
        <trans-unit id="119" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String)">
          <source>The <ph id="ph1">`message`</ph> string</source>
          <target state="translated"><ph id="ph1">`message`</ph>字串</target>       </trans-unit>
        <trans-unit id="120" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>The error message that explains the reason for the exception.</source>
          <target state="translated">解釋例外狀況原因的錯誤訊息。</target>       </trans-unit>
        <trans-unit id="121" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">做為目前例外狀況發生原因的例外狀況。</target>       </trans-unit>
        <trans-unit id="122" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>InnerException<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          <target state="translated">如果 <bpt id="p1">&lt;c&gt;</bpt>InnerException<ept id="p1">&lt;/c&gt;</ept> 參數不是 <ph id="ph1">&lt;see langword="null" /&gt;</ph>，則目前的例外狀況會在處理內部例外的 <ph id="ph2">&lt;see langword="catch" /&gt;</ph> 區塊中引發。</target>       </trans-unit>
        <trans-unit id="123" translate="yes" xml:space="preserve" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.RemotingTimeoutException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">使用指定的錯誤訊息以及造成此例外狀況的內部例外狀況的參考，初始化 <ph id="ph1">&lt;see cref="T:System.Runtime.Remoting.RemotingTimeoutException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="124" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>An exception that is thrown as a direct result of a previous exception must include a reference to the previous exception in the <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property.</source>
          <target state="translated">做為前一個例外狀況直接結果必須包括在前一個例外狀況的參考就會擲回的例外狀況<ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph>屬性。</target>       </trans-unit>
        <trans-unit id="125" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>The <ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property returns the same value that is passed into the constructor, or <ph id="ph2">`null`</ph> if the <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph> property does not supply the inner exception value to the constructor.</source>
          <target state="translated"><ph id="ph1">&lt;xref:System.Exception.InnerException%2A&gt;</ph> 屬性會傳回與傳入建構函式中相同的值；如果 <ph id="ph2">`null`</ph> 屬性沒有提供內部例外值給建構函式，則傳回 <ph id="ph3">&lt;xref:System.Exception.InnerException%2A&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="126" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>The following table shows initial property values for an instance of the <ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph> class:</source>
          <target state="translated">下表顯示的執行個體的初始屬性值<ph id="ph1">&lt;xref:System.Runtime.Remoting.RemotingTimeoutException&gt;</ph>類別：</target>       </trans-unit>
        <trans-unit id="127" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>Property</source>
          <target state="translated">屬性</target>       </trans-unit>
        <trans-unit id="128" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>Value</source>
          <target state="translated">值</target>       </trans-unit>
        <trans-unit id="129" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>The inner exception reference</source>
          <target state="translated">內部例外狀況參考</target>       </trans-unit>
        <trans-unit id="130" translate="yes" xml:space="preserve" extradata="MT" uid="M:System.Runtime.Remoting.RemotingTimeoutException.#ctor(System.String,System.Exception)">
          <source>The error message string</source>
          <target state="translated">錯誤訊息字串</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>