<?xml version="1.0" encoding="utf-8"?>
<xliff xmlns="urn:oasis:names:tc:xliff:document:1.2" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.2" xsi:schemaLocation="urn:oasis:names:tc:xliff:document:1.2 xliff-core-1.2-transitional.xsd">
  <file datatype="xml" original="XamlInternalException.xml" source-language="en-US" target-language="zh-TW">
    <header>
      <tool tool-id="mdxliff" tool-name="mdxliff" tool-version="1.0-15c36f0" tool-company="Microsoft" />
      <xliffext:skl_file_name xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">02cd5861-7ce2-4a82-b358-31f8435a0ac50729fa9645baf6a20d37770d139f103712c6612f.skl</xliffext:skl_file_name>
      <xliffext:version xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">1.2</xliffext:version>
      <xliffext:ms.openlocfilehash xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">0729fa9645baf6a20d37770d139f103712c6612f</xliffext:ms.openlocfilehash>
      <xliffext:ms.sourcegitcommit xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">d31dc2ede16f6f7bc64e90d9f897ff54c4e3869b</xliffext:ms.sourcegitcommit>
      <xliffext:ms.lasthandoff xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">04/03/2018</xliffext:ms.lasthandoff>
      <xliffext:moniker_ids xmlns:xliffext="urn:microsoft:content:schema:xliffextensions">netframework-4.5.1,netframework-4.5.2,netframework-4.5,netframework-4.6.1,netframework-4.6.2,netframework-4.6,netframework-4.7.1,netframework-4.7</xliffext:moniker_ids>
    </header>
    <body>
      <group id="content" extype="content">
        <trans-unit id="101" translate="yes" xml:space="preserve" uid="T:System.Xaml.XamlInternalException">
          <source>The exception that is thrown for internal inconsistencies that occur during XAML reading and XAML writing.</source>
          <target state="translated">在 XAML 讀取或 XAML 寫入期間，針對內部不一致情況所擲回的例外狀況。</target>       </trans-unit>
        <trans-unit id="102" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>This exception is usually thrown only when some aspect of the XAML reader or XAML writer system was extended by your code, and inconsistencies or implementation problems occurred that were passed on to the .NET Framework XAML Services system code.</source>
          <target state="translated">只有在某種程度的 XAML 讀取器或 XAML 寫入器系統已擴充您的程式碼，並不一致或實作問題發生傳遞至.NET Framework XAML 服務的系統程式碼時，通常會擲回這個例外狀況。</target>       </trans-unit>
        <trans-unit id="103" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Exceptions that might originate from third parties, such as parsing XAML and encountering errors in the XAML, should not throw <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>, and should instead throw other exceptions such as <ph id="ph2">&lt;xref:System.Xaml.XamlParseException&gt;</ph> or <ph id="ph3">&lt;xref:System.Xaml.XamlObjectWriterException&gt;</ph>.</source>
          <target state="translated">不應該擲回例外狀況可能來自第三方，例如剖析 XAML 和發生錯誤，在 XAML 中、 <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>，並且應該改為擲回其他例外狀況例如<ph id="ph2">&lt;xref:System.Xaml.XamlParseException&gt;</ph>或<ph id="ph3">&lt;xref:System.Xaml.XamlObjectWriterException&gt;</ph>。</target>       </trans-unit>
        <trans-unit id="104" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>If you are writing code that extends .NET Framework XAML Services, in particular, if you are writing code for a XAML reader or XAML writer implementation, you should maintain this distinction between <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> and the other XAML-related exceptions.</source>
          <target state="translated">如果您要撰寫程式碼將.NET Framework XAML 服務的擴充，特別是，如果您要撰寫程式碼的 XAML 讀取器或 XAML 寫入器實作，您應該維護這個區別<ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>和其他 XAML 相關例外狀況。</target>       </trans-unit>
        <trans-unit id="105" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Your code should only throw <ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph> in cases where further extension of your class violates some design principle or implementation pattern that your callable code defines.</source>
          <target state="translated">您的程式碼應該只會擲回<ph id="ph1">&lt;xref:System.Xaml.XamlInternalException&gt;</ph>在其中進一步的延伸模組，您的類別，違反了您可呼叫的程式碼會定義一些設計原則或實作模式的情況下。</target>       </trans-unit>
        <trans-unit id="106" translate="yes" xml:space="preserve" extradata="MT" uid="T:System.Xaml.XamlInternalException">
          <source>Your code should throw other XAML-specific exceptions for exception cases where your XAML reader or XAML writer implementation is used without extension and is used to load third-party XAML, third-party XAML schema context, and so on.</source>
          <target state="translated">您的程式碼應該擲回例外狀況，其中您的 XAML 讀取器或 XAML 寫入器實作使用不含副檔名，並且用來載入 XAML 第三方、 第三方 XAML 結構描述內容，等其他 XAML 特有的例外狀況。</target>       </trans-unit>
        <trans-unit id="107" translate="yes" xml:space="preserve" uid="T:System.Xaml.XamlInternalException">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class.</source>
          <target state="translated">初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="108" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a system-supplied message that describes the error.</source>
          <target state="translated">以系統提供的錯誤說明訊息，初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="109" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String)">
          <source>The message that describes the exception.</source>
          <target state="translated">說明例外狀況的訊息。</target>       </trans-unit>
        <trans-unit id="110" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a specified message that describes the error.</source>
          <target state="translated">使用指定的錯誤說明訊息，初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="111" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The object that holds the serialized object data.</source>
          <target state="translated">存放序列物件資料的物件。</target>       </trans-unit>
        <trans-unit id="112" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>The contextual information about the source or destination.</source>
          <target state="translated">關於來源或目的端的內容資訊。</target>       </trans-unit>
        <trans-unit id="113" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with serialized data.</source>
          <target state="translated">使用序列化資料，初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
        <trans-unit id="114" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>The message that describes the exception.</source>
          <target state="translated">說明例外狀況的訊息。</target>       </trans-unit>
        <trans-unit id="115" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>The exception that is the cause of the current exception.</source>
          <target state="translated">做為目前例外狀況發生原因的例外狀況。</target>       </trans-unit>
        <trans-unit id="116" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>If the <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> parameter is not <ph id="ph1">&lt;see langword="null" /&gt;</ph>, the current exception is raised in a <ph id="ph2">&lt;see langword="catch" /&gt;</ph> block that handles the inner exception.</source>
          <target state="translated">如果 <bpt id="p1">&lt;c&gt;</bpt>innerException<ept id="p1">&lt;/c&gt;</ept> 參數不是 <ph id="ph1">&lt;see langword="null" /&gt;</ph>，則目前的例外狀況會在處理內部例外的 <ph id="ph2">&lt;see langword="catch" /&gt;</ph> 區塊中引發。</target>       </trans-unit>
        <trans-unit id="117" translate="yes" xml:space="preserve" uid="M:System.Xaml.XamlInternalException.#ctor(System.String,System.Exception)">
          <source>Initializes a new instance of the <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> class with a specified error message and a reference to the inner exception that is the cause of this exception.</source>
          <target state="translated">使用指定的錯誤訊息以及造成此例外狀況的內部例外狀況的參考，初始化 <ph id="ph1">&lt;see cref="T:System.Xaml.XamlInternalException" /&gt;</ph> 類別的新執行個體。</target>       </trans-unit>
      </group>
    </body>
  </file>
</xliff>