### <a name="systemthreadingtaskstask-no-longer-throw-objectdisposedexception-after-object-is-disposed"></a><span data-ttu-id="d745e-101">System.Threading.Tasks.Task 不再之後會擲回 ObjectDisposedException 處置物件</span><span class="sxs-lookup"><span data-stu-id="d745e-101">System.Threading.Tasks.Task no longer throw ObjectDisposedException after object is disposed</span></span>

|   |   |
|---|---|
|<span data-ttu-id="d745e-102">詳細資料</span><span class="sxs-lookup"><span data-stu-id="d745e-102">Details</span></span>|<span data-ttu-id="d745e-103">除了<xref:System.Threading.Tasks.Task.System%23IAsyncResult%23AsyncWaitHandle>，<xref:System.Threading.Tasks.Task?displayProperty=name>方法不會再擲回<xref:System.ObjectDisposedException?displayProperty=name>處置物件後的例外狀況。這項變更支援使用快取的工作。</span><span class="sxs-lookup"><span data-stu-id="d745e-103">Except for <xref:System.Threading.Tasks.Task.System%23IAsyncResult%23AsyncWaitHandle>, <xref:System.Threading.Tasks.Task?displayProperty=name> methods no longer throw an <xref:System.ObjectDisposedException?displayProperty=name> exception after the object is disposed.This change supports the use of cached tasks.</span></span> <span data-ttu-id="d745e-104">例如，方法可能傳回快取的工作來表示已完成的作業，而不配置新的工作。</span><span class="sxs-lookup"><span data-stu-id="d745e-104">For example, a method can return a cached task to represent an already completed operation instead of allocating a new task.</span></span> <span data-ttu-id="d745e-105">舊版的 .NET Framework 並未提供這項功能，因為工作的任何消費者都可能會處置它，使它變得無法使用。</span><span class="sxs-lookup"><span data-stu-id="d745e-105">This was impossible in previous .NET Framework versions, because any consumer of the task could dispose of it, which rendered it unusable.</span></span>|
|<span data-ttu-id="d745e-106">建議</span><span class="sxs-lookup"><span data-stu-id="d745e-106">Suggestion</span></span>|<span data-ttu-id="d745e-107">請注意工作方法可能不會擲回<xref:System.ObjectDisposedException?displayProperty=name>情況下在處置物件。</span><span class="sxs-lookup"><span data-stu-id="d745e-107">Be aware that Task methods may no longer throw <xref:System.ObjectDisposedException?displayProperty=name> in cases when the object is disposed.</span></span> <span data-ttu-id="d745e-108">如果應用程式已根據知道工作已處置此例外狀況，應該更新明確檢查工作的狀態使用<xref:System.Threading.Tasks.Task.Status>。</span><span class="sxs-lookup"><span data-stu-id="d745e-108">If an app was depending on this exception to know that a task was disposed, it should be updated to explicitly check the task's status using <xref:System.Threading.Tasks.Task.Status>.</span></span>|
|<span data-ttu-id="d745e-109">範圍</span><span class="sxs-lookup"><span data-stu-id="d745e-109">Scope</span></span>|<span data-ttu-id="d745e-110">次要</span><span class="sxs-lookup"><span data-stu-id="d745e-110">Minor</span></span>|
|<span data-ttu-id="d745e-111">版本</span><span class="sxs-lookup"><span data-stu-id="d745e-111">Version</span></span>|<span data-ttu-id="d745e-112">4.5</span><span class="sxs-lookup"><span data-stu-id="d745e-112">4.5</span></span>|
|<span data-ttu-id="d745e-113">類型</span><span class="sxs-lookup"><span data-stu-id="d745e-113">Type</span></span>|<span data-ttu-id="d745e-114">執行階段</span><span class="sxs-lookup"><span data-stu-id="d745e-114">Runtime</span></span>|

